name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          pwd
          echo $GITHUB_WORKSPACE
          ls -laR
          ls -laR $GITHUB_WORKSPACE
          mount
          lsblk
          df -h
          free -h
          cat /proc/cpuinfo
          cat /proc/meminfo
      - run: |
          dd if=/dev/urandom bs=1M count=100 of=test
      - uses: actions/upload-artifact@v2
        with:
          name: Test1
          path: test
      - run: |
          sudo mount -t tmpfs none /tmp
          sudo mount -t tmpfs none "$GITHUB_WORKSPACE"
          cd /
          cd "$GITHUB_WORKSPACE"
          dd if=/dev/urandom bs=1M count=100 of=test
      - uses: actions/upload-artifact@v2
        with:
          name: Test2
          path: test
  foo:
    runs-on: ubuntu-18.04
    needs:
      test
    outputs:
      needPatch: ${{ steps.patchNeeded.outputs.needPatch }}
    steps:
    - id: patchNeeded
      run: |
        echo "::set-output name=needPatch::false"

  bar:
    runs-on: ubuntu-18.04
    needs:
      foo
    if: needs.foo.outputs.needPatch == 'true'
    steps:
      - name: Test
        run: |
          echo Bar

  barz:
    runs-on: ubuntu-18.04
    needs:
    - test
    - bar
    if: always() && needs.test.result == 'success' && needs.bar.result != 'failure'
    steps:
      - name: Test
        run: |
          echo Barz
      - name: Test if
        run: |
          echo Bar!!
        if: needs.kpatch.result == 'success'
